trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Install Node.js
  - task: UseNode@1
    inputs:
      version: '16.x'

  # Install dependencies (if any)
  - script: |
      npm install
    displayName: 'Install dependencies'

 
  # Archive files for deployment
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/greet.zip'
      replaceExistingArchive: true

  # Publish the artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/greet.zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'MyServiceConnection'  # You will configure this in the portal
      appType: 'webAppLinux'                               # Use 'webApp' for Windows, 'webAppLinux' for Linux
      appName: 'MyGreetApp'                                # Your Azure Web App name
      package: '$(Build.ArtifactStagingDirectory)/greet.zip'         # This is the directory where the app is located
