trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildJob
  displayName: 'Build the project'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'
  
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

- job: TestJob
  displayName: 'Run tests'
  dependsOn: BuildJob  # This forces TestJob to wait until BuildJob completes
  steps:
  - script: |
      npm install
      npm test
    displayName: 'Install and run tests'
